defaults:
  - default

accelerator:
  _target_: lightning_npu.accelerators.npu.NPUAccelerator

strategy: 
  _target_: lightning_npu.strategies.npu_parallel.NPUParallelStrategy

plugins:
  _target_: lightning_npu.plugins.npu.NpuMixedPrecisionPlugin
  amp_level: O2
  
devices: null
num_nodes: 1
sync_batchnorm: True
