# https://pytorch-lightning.readthedocs.io/en/latest/api/pytorch_lightning.callbacks.TQDMProgressBar.html

# Create a progress bar with tqdm.
# Look at the above link for more detailed information.
rich_progress_bar:
  _target_: pytorch_lightning.callbacks.TQDMProgressBar
  refresh_rate: 20
